# Generated by Django 5.1.4 on 2025-01-03 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrecord',
            name='sale_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
