# Generated by Django 5.1.4 on 2025-01-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleagent',
            name='allowed_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='saleagent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleagent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
