# Generated by Django 5.1.4 on 2025-01-05 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='old_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.clientrecord'),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
