# Generated by Django 5.1.4 on 2025-01-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sessionlog_new_value_sessionlog_old_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_payment_date', models.DateField()),
                ('payment_duration_months', models.IntegerField()),
                ('sale_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sales.saleagent')),
            ],
        ),
    ]
