# Generated by Django 5.1.4 on 2025-01-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleagentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleagentprofile',
            name='sale_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sales.saleagent'),
        ),
    ]
