# Generated by Django 5.1.4 on 2025-01-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_category_subcategory_clientrecord_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrecord',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='clientrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_records', to='sales.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
